#### Presupuesto para la atención a emergencias por desastres

```{r include=FALSE}
folder='departamentos'
fileName='DEPARTAMENTO.shp' # nivel 2 son provincias
fileToRead=file.path(folder,fileName)

library(rgdal)
PeruDepa <- rgdal::readOGR(fileToRead,stringsAsFactors=FALSE)
```

```{r include=FALSE}
data = read.csv("0068_Final.csv")
```

##### 1. Asignación presupuestal a nivel regional para la atención a desastres

```{r include=FALSE}
dataPIM = data[,c(1,2,5,8,11,14,17)]
```

```{r include=FALSE}
names(dataPIM) = c("REGION","PIM_2018","PIM_2017","PIM_2016","PIM_2015","PIM_2014","PIM_2013")
```

```{r include=FALSE}
row.names(dataPIM) = dataPIM$REGION
dataPIM = dataPIM[,-c(1)]
```

```{r include=FALSE}
prov_sub.scaled<- scale(dataPIM)
```

```{r include=FALSE}
prov_sub_d <- dist(prov_sub.scaled)
```

```{r include=FALSE}
prov_sub_clusters=hclust(prov_sub_d)
```

```{r include=FALSE}
library(NbClust)

#usar aqui las variables normalizadas: prov_sub.scaled
nb <- NbClust(prov_sub.scaled, method = "complete") # 'hclust' usa este método por defecto

```

```{r include=FALSE}
library(factoextra) # toma su tiempo
# resultado de factoExtra (FE)
prov_sub_clusters_FE <- eclust(prov_sub.scaled, FUNcluster ="hclust", k = 4,
                method = "complete", graph = FALSE) 
fviz_dend(prov_sub_clusters_FE, rect = TRUE, show_labels = FALSE) 

```
```{r include=FALSE}
siluetas <-prov_sub_clusters_FE$silinfo$widths
```

```{r include=FALSE}
dataPIM = merge(dataPIM, siluetas, by = 0)
```

```{r include=FALSE}
x=aggregate(cbind(PIM_2018,PIM_2017,PIM_2016,PIM_2015,PIM_2014,PIM_2013) ~ cluster, data=dataPIM,FUN=mean)
```

```{r include=FALSE}
#4 es mejor y 1 es peor
x$f = x$PIM_2018+x$PIM_2017+x$PIM_2016+x$PIM_2015+x$PIM_2014+x$PIM_2013
```

```{r include=FALSE}
folder='departamentos'
fileName='DEPARTAMENTO.shp' # nivel 2 son provincias
fileToRead=file.path(folder,fileName)

library(rgdal)
PeruDepa <- rgdal::readOGR(fileToRead,stringsAsFactors=FALSE)
```

```{r include=FALSE}
PeruDepa=merge(PeruDepa,dataPIM,by.x="DEPARTAMEN", by.y = "Row.names",all.x=TRUE)
```

```{r fig.height = 6, echo=FALSE,warning=FALSE}
#Mapa de latente:
paleta=c('seagreen1','gray',"palevioletred1","orange") #colores
plot(PeruDepa,col='white',border=T) 
plot(PeruDepa,
     col=paleta[PeruDepa$cluster],
     border='NA',add=T)

legend("right",
       title='Prespuesto para la\natencion a desastres (2013-2018)',
       legend=c(paste0("Bajo"),
                paste0("Medio"),
                paste0("Alto"),
                paste0("Muy alto")
                ),
           fill=c('seagreen1','gray',"palevioletred1","orange"),cex=0.8,bty = "n")
```

##### 2. Ejecución presupuestal a nivel regional para la atención a desastres

```{r include=FALSE}
dataEJEC = data[,c(1,4,7,10,13,16,19)]
```

```{r include=FALSE}
names(dataEJEC) = c("REGION","AVANCE2018","AVANCE2017","AVANCE2016","AVANCE2015","AVANCE2014","AVANCE2013")
```

```{r include=FALSE}
row.names(dataEJEC) = dataEJEC$REGION
dataEJEC = dataEJEC[,-c(1)]
```

```{r include=FALSE}
prov_sub.scaled<- scale(dataEJEC)
```

```{r include=FALSE}
prov_sub_d <- dist(prov_sub.scaled)
```

```{r include=FALSE}
prov_sub_clusters=hclust(prov_sub_d)
```

```{r include=FALSE}
library(NbClust)

#usar aqui las variables normalizadas: prov_sub.scaled
nb <- NbClust(prov_sub.scaled, method = "complete") # 'hclust' usa este método por defecto

```

```{r include=FALSE}
library(factoextra) # toma su tiempo
# resultado de factoExtra (FE)
prov_sub_clusters_FE <- eclust(prov_sub.scaled, FUNcluster ="hclust", k = 4,
                method = "complete", graph = FALSE) 
fviz_dend(prov_sub_clusters_FE, rect = TRUE, show_labels = FALSE) 

```

```{r include=FALSE}
siluetas <-prov_sub_clusters_FE$silinfo$widths
```

```{r include=FALSE}
dataEJEC = merge(dataEJEC,siluetas, by = 0)
```

```{r include=FALSE}
x=aggregate(cbind(AVANCE2018,AVANCE2017,AVANCE2016,AVANCE2015,AVANCE2014,AVANCE2013) ~ cluster, data=dataEJEC,FUN=mean)
```

```{r include=FALSE}
x$f = x$AVANCE2018+x$AVANCE2017+x$AVANCE2016+x$AVANCE2015+x$AVANCE2014+x$AVANCE2013
```

```{r include=FALSE}
dataEJEC$cluster=factor(car::recode(dataEJEC$cluster, "1=4; 3=3; 4=2; 2=1"), ordered=T)
```

```{r include=FALSE}
folder='departamentos'
fileName='DEPARTAMENTO.shp' # nivel 2 son provincias
fileToRead=file.path(folder,fileName)

library(rgdal)
PeruDepa <- rgdal::readOGR(fileToRead,stringsAsFactors=FALSE)
```

```{r include=FALSE}
PeruDepa=merge(PeruDepa,dataEJEC,by.x="DEPARTAMEN", by.y = "Row.names",all.x=TRUE)
```

```{r fig.height = 6, echo=FALSE,warning=FALSE}
#Mapa de latente:
paleta=c('seagreen1','gray',"palevioletred1","orange") #colores
plot(PeruDepa,col='white',border=T) 
plot(PeruDepa,
     col=paleta[PeruDepa$cluster],
     border='NA',add=T)

legend("right",
       title='Ejecucion presupuestal para la\natencion a desastres (2013-2018)',
       legend=c(paste0("Bajo"),
                paste0("Medio"),
                paste0("Alto"),
                paste0("Muy Alto")
                ),
           fill=c('seagreen1','gray',"palevioletred1","orange"),cex=0.8,bty = "n")
```

#### 2. FONDES (2017-2019)

```{r include=FALSE}
folder='departamentos'
fileName='DEPARTAMENTO.shp' # nivel 2 son provincias
fileToRead=file.path(folder,fileName)

library(rgdal)
PeruDepa <- rgdal::readOGR(fileToRead,stringsAsFactors=FALSE)
```

```{r include=FALSE}
data=read.csv("FONDES.csv", stringsAsFactors = T)
```

```{r include=FALSE}
names(data) = c("REGION","ASIGNA_2017","AVANCE_2017","ASIGNA_2018","AVANCE_2018","ASIGNA_2019","CLUST")
```

```{r include=FALSE}
data$AVANCE_2017 = substr(data$AVANCE_2017,4,50)
data$AVANCE_2018 = substr(data$AVANCE_2018,4,50)
```

```{r include=FALSE}
data$ASIGNA_2017 = as.numeric(data$ASIGNA_2017)
data$ASIGNA_2018 = as.numeric(data$ASIGNA_2018)
data$ASIGNA_2019 = as.numeric(data$ASIGNA_2019)
data$AVANCE_2017 = as.numeric(data$AVANCE_2017)
data$AVANCE_2018 = as.numeric(data$AVANCE_2018)
```

```{r include=FALSE}
data$CLUST = factor(data$CLUST, ordered = T, levels = c(1:3))
```

```{r include=FALSE}
data$CLUST=factor(car::recode(data$CLUST, "1=2; 3=1; 2=3"), ordered=T)
```

```{r include=FALSE}
etiquetas=c(1,2,3)
data$AVANCE_2017_ORD = cut(data$AVANCE_2017,
                           breaks = 3,
                           labels = etiquetas,
                           ordered_result = T)
```

```{r include=FALSE}
etiquetas=c(1,2,3)
data$AVANCE_2018_ORD = cut(data$AVANCE_2018,
                           breaks = 3,
                           labels = etiquetas,
                           ordered_result = T)
```

```{r include=FALSE}
PeruDepa=merge(PeruDepa,data,by.x="DEPARTAMEN", by.y = "REGION",all.x=TRUE)
```

```{r fig.height = 6, echo=FALSE,warning=FALSE}
#Mapa de latente:
paleta=c("khaki1","gold","goldenrod2","goldenrod4") #colores
plot(PeruDepa,col='white',border=T) 
plot(PeruDepa,
     col=paleta[PeruDepa$CLUST],
     border='NA',add=T)

legend("right",
       title='FONDES (2017-2019)',
       legend=c(paste0("Bajo"),
                paste0("Medio"),
                paste0("Alto")
                ),
           fill=c("khaki1","gold","goldenrod2","goldenrod4"),cex=0.8,bty = "n")
```

```{r fig.height = 6, echo=FALSE,warning=FALSE}
#Mapa de latente:
paleta=c('seagreen1','gray',"palevioletred1") #colores
plot(PeruDepa,col='white',border=T) 
plot(PeruDepa,
     col=paleta[PeruDepa$AVANCE_2017_ORD],
     border='NA',add=T)

legend("right",
       title='Avance FONDES (2017)',
       legend=c(paste0("Bajo"),
                paste0("Medio"),
                paste0("Alto")
                ),
           fill=c('seagreen1','gray',"palevioletred1"),cex=0.8,bty = "n")
```

```{r fig.height = 6, echo=FALSE,warning=FALSE}
#Mapa de latente:
paleta=c('seagreen1','gray',"palevioletred1") #colores
plot(PeruDepa,col='white',border=T) 
plot(PeruDepa,
     col=paleta[PeruDepa$AVANCE_2018_ORD],
     border='NA',add=T)

legend("right",
       title='Avance FONDES (2018)',
       legend=c(paste0("Bajo"),
                paste0("Medio"),
                paste0("Alto")
                ),
           fill=c('seagreen1','gray',"palevioletred1"),cex=0.8,bty = "n")
```
