```{r include=FALSE}
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
```

```{r include=FALSE}
text <- readLines("Discursos Fujimori (1990-2000).txt")
```

```{r include=FALSE}
docs <- Corpus(VectorSource(text))
```

```{r include=FALSE}
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
```

```{r include=FALSE}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("que","los","del","las","con","por","para","una","como","esta","este","mas","a<c3><b1>os","han","pero","sus","sin","a<c3><b1>os","a<c3><b1>o","año","años","estos","son","tambien","todo","sido","sino","esa","desde","solo","entre","asi","ese","eso","asimismo")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
```

```{r include=FALSE}
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 30)
```

```{r fig.height = 6, echo=FALSE,warning=FALSE}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=70, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```

```{r include=FALSE}
findFreqTerms(dtm, lowfreq = 100)
```

```{r include=FALSE}
findAssocs(dtm, terms = "sector", corlimit = 0.2)
```

```{r fig.height = 6, echo=FALSE,warning=FALSE}
barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Most frequent words",
        ylab = "Word frequencies")
```

